# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Environment variables
ENV MYSQL_ROOT_PASSWORD=pokuaah
ENV MYSQL_DATABASE=blogAppDb;

# Expose the MySQL port
EXPOSE 3306

# Default command to run when the container starts
CMD ["mysqld"]